//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_ST_COVERAGE_GROUP_DETAIL_Result
    {
        public int Corp_Id { get; set; }
        public int Group_Id { get; set; }
        public int Coverage_Type_Id { get; set; }
        public int Coverage_Id { get; set; }
        public Nullable<int> Coverage_Limit_Min { get; set; }
        public Nullable<int> Coverage_Limit_Max { get; set; }
    }
}
