//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_PRODUCTOS_CLIENTES_DASH_Result
    {
        public int Corp_Id { get; set; }
        public Nullable<int> COD_OWNER { get; set; }
        public int COD_PRODUCTO { get; set; }
        public string PRODUCTO { get; set; }
        public int COD_LINEA_TIPO { get; set; }
        public string Categoria { get; set; }
        public int COD_LINEA_PRODUCTO { get; set; }
        public string LINEA_PRODUCTO { get; set; }
        public string POLICY_NO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string LINEA_TIPO { get; set; }
        public Nullable<int> ID_PAIS { get; set; }
        public string PAIS { get; set; }
        public Nullable<int> ID_OFICINA { get; set; }
        public string OFICINA { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string DESCRIPCION_COMP { get; set; }
        public Nullable<int> ID_CIUDAD { get; set; }
        public string CIUDAD { get; set; }
        public Nullable<int> COD_AGENT { get; set; }
        public string AGENT_NAME { get; set; }
    }
}
