//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_CardNet_Settings_Result
    {
        public int Configuration_Type_Id { get; set; }
        public int Configuration_Id { get; set; }
        public int Facility_Id { get; set; }
        public string Acquiring_Institution_Code { get; set; }
        public string Merchant_Type { get; set; }
        public string Merchant_Number { get; set; }
        public string Merchant_Terminal { get; set; }
        public string Merchant_Number_Amex { get; set; }
        public string Merchant_Terminal_Amex { get; set; }
        public string Url { get; set; }
        public string Currency_Code { get; set; }
    }
}
