//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReAssignNCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysFlexSegurosEntities : DbContext
    {
        public SysFlexSegurosEntities()
            : base("name=SysFlexSegurosEntities")
        {
            IN_DocumentoCobrar = Set<IN_DocumentoCobrar>();
            ReassignNCF_log = Set<ReassignNCF_log>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<IN_DocumentoCobrar> IN_DocumentoCobrar { get; set; }
        internal virtual DbSet<ReassignNCF_log> ReassignNCF_log { get; set; }
        public virtual DbSet<Tipo_Movimiento> Tipo_Movimiento { get; set; }
    }
}
