//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_COVERAGES_OWN_DAMAGE_Result
    {
        public string Poliza { get; set; }
        public long Vehiculo { get; set; }
        public string Vehiculo_desc { get; set; }
        public string Plan { get; set; }
        public int Group_Id { get; set; }
        public int Corp_Id { get; set; }
        public int Region_Id { get; set; }
        public int Country_Id { get; set; }
        public int Domesticreg_Id { get; set; }
        public int State_Prov_Id { get; set; }
        public int City_Id { get; set; }
        public int Office_Id { get; set; }
        public int Case_Seq_No { get; set; }
        public int Hist_Seq_No { get; set; }
        public Nullable<decimal> Incendio_y_robo { get; set; }
        public Nullable<decimal> Colision_y_vuelco { get; set; }
        public Nullable<decimal> Riesgo_comprensivo { get; set; }
    }
}
