
namespace Entity.UnderWriting.Entities
{
    public class DropDown
    {
        public int? CorpId { get; set; }
        public int? RegionId { get; set; }
        public int? CountryId { get; set; }
        public int? DomesticregId { get; set; }
        public int? StateProvId { get; set; }
        public int? CityId { get; set; }
        public int? OfficeId { get; set; }
        public int? CaseSeqNo { get; set; }
        public int? HistSeqNo { get; set; }
        public string AgentName { get; set; }
        public string CityDesc { get; set; }
        public string DirTypeShortDesc { get; set; }
        public int? DirectoryTypeId { get; set; }
        public string GlobalCountryDesc { get; set; }
        public string GlobalCountryDescTimeZone { get; set; }
        public int? MaritalStatId { get; set; }
        public string MaritalStatusDesc { get; set; }
        public string OccupationDesc { get; set; }
        public int? OccupationId { get; set; }
        public int? OccupGroupTypeId { get; set; }
        public string OfficeDesc { get; set; }
        public string PolicyStatusDesc { get; set; }
        public int? PolicyStatusId { get; set; }
        public int? ContactId { get; set; }
        public int? ContactRoleTypeId { get; set; }
        public string RoleDesc { get; set; }
        public int? SmokerId { get; set; }
        public string SmokerDesc { get; set; }
        public string GenderId { get; set; }
        public string GenderDesc { get; set; }
        public int? ContactTypeId { get; set; }
        public string ContactTypeIdDesc { get; set; }
        public int? RelationshipId { get; set; }
        public string RelationshipDesc { get; set; }
        public string StateProvDesc { get; set; }
        public string OccupationGroupDesc { get; set; }
        public int? AmmendTypeId { get; set; }
        public string AmmendTypeDesc { get; set; }
        public int? InsuredScopeId { get; set; }
        public string InsuredScopeDesc { get; set; }
        public int? RiderTypeId { get; set; }
        public string CodeName { get; set; }
        public int? RiderStatusId { get; set; }
        public string RiderStatusDesc { get; set; }
        public int? PaymentStatusId { get; set; }
        public string PaymentStatusDesc { get; set; }
        public string PolicyNo { get; set; }
        public string ValueField { get; set; }
        public int? RequirementCatId { get; set; }
        public string RequirementCatDesc { get; set; }
        public int? RequirementTypeId { get; set; }
        public string RequirementTypeDesc { get; set; }
        public int? ExcerciseId { get; set; }
        public string ExcerciseDesc { get; set; }
        public int? DrugId { get; set; }
        public string DrugDesc { get; set; }
        public int? RiskGroupId { get; set; }
        public int? RiskDetId { get; set; }
        public int? PageId { get; set; }
        public int? GridId { get; set; }
        public int? ElementId { get; set; }
        public string ElementDesc { get; set; }
        public string RiskGroupDesc { get; set; }
        public string RiskDetDesc { get; set; }
        public int? TableTypeId { get; set; }
        public int? RatingId { get; set; }
        public string RatingValue { get; set; }
        public int? RequirementId { get; set; }
        public int? MedicalTestId { get; set; }
        public int? ColumnId { get; set; }
        public int? RiskTypeId { get; set; }
        public int? CurrencyId { get; set; }
        public string CurrencyDesc { get; set; }
        public int? BlTypeId { get; set; }
        public int? BlId { get; set; }
        public string BlDesc { get; set; }
        public int? ProductId { get; set; }
        public string ProductDesc { get; set; }
        public int? PolicySerieId { get; set; }
        public string SerieCode { get; set; }
        public string SerieDesc { get; set; }
        public int? ProfileTypeId { get; set; }
        public string ProfileTypeDesc { get; set; }
        public int? PaymentFreqTypeId { get; set; }
        public string PaymentFreqTypeDesc { get; set; }
        public int? NoteReferenceTypeId { get; set; }
        public string NoteReferenceTypeDesc { get; set; }
        public int? DocTypeId { get; set; }
        public int? DocCategoryId { get; set; }
        public string DocCategoryDesc { get; set; }
        public int? Counts { get; set; }
        public int? ContributionTypeId { get; set; }
        public string ContributionTypeDesc { get; set; }
        public int? StepTypeId { get; set; }
        public int? StepId { get; set; }
        public string StepDesc { get; set; }
        public string StepCode { get; set; }
        public int? PaymentTypeId { get; set; }
        public string PaymentDesc { get; set; }
        public int? PaymentSourceId { get; set; }
        public string PaymentSourceDesc { get; set; }
        public int? PaymentSourceTypeId { get; set; }
        public int? CardTypeId { get; set; }
        public string CardTypeDesc { get; set; }
        public int? AccountTypeId { get; set; }
        public string AccountDesc { get; set; }
        public int? PaymentControlId { get; set; }
        public int? AgentId { get; set; }
        public int? BankId { get; set; }
        public string BankDesc { get; set; }
        public string AbaNumber { get; set; }
        public int? ActionId { get; set; }
        public string ActionDesc { get; set; }
        public int? NoteTypeId { get; set; }
        public string NoteTypeDesc { get; set; }
        public int? HomeStatusId { get; set; }
        public string HomeStatusDesc { get; set; }
        public string Namekey { get; set; }
        public int? LaborPlayedId { get; set; }
        public string LaborPlayedDesc { get; set; }
        public int? ScaleId { get; set; }
        public int? ScaleTypeId { get; set; }
        public string ScaleDesc { get; set; }
        public int? QuestionnaireId { get; set; }
        public int? QuestionId { get; set; }
        public int? DiseaseId { get; set; }
        public string DiseaseDesc { get; set; }
        public bool? Modifiable { get; set; }
        public int? ProductTypeId { get; set; }
        public string RiskTypeDesc { get; set; }
        public int? FormId { get; set; }
        public string FormDesc { get; set; }
        public int? FormCategoryId { get; set; }
        public string FormCatDesc { get; set; }
        public int? RiderId { get; set; }
        public int? ExclusionTypeId { get; set; }
        public string ExclusionTypeDesc { get; set; }
        public int? ExclusionId { get; set; }
        public string ExclusionDesc { get; set; }
        public int? CreditId { get; set; }
        public string CreditDesc { get; set; }
        public int? CreditReasonId { get; set; }
        public string CreditReasonDesc { get; set; }
        public int? RequestedBy { get; set; }
        public string UnderwritingName { get; set; }
        public int? UnderwritingId { get; set; }
        public int? LanguageId { get; set; }
        public string LanguageDesc { get; set; }
        public string ImageName { get; set; }
        public int? CreditTypeId { get; set; }
        public int? RatingTypeId { get; set; }
        public string RatingTypeDesc { get; set; }
        public bool? PrintStatus { get; set; }
        public int? StepReasonId { get; set; }
        public string StepReasonDesc { get; set; }
        public int? BloodTypeId { get; set; }
        public string BloodTypeDesc { get; set; }
        public int? RejectReasonId { get; set; }
        public string RejectReasonDesc { get; set; }
        public int? ProviderId { get; set; }
        public int? TransactionTypeCatalogId { get; set; }
        public int? ProviderTransactionTypeId { get; set; }
        public string TransactionTypeCatalogDesc { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseDesc { get; set; }
        public string ConfigurationValue { get; set; }
        public int? CompanyId { get; set; }
        public string CompanyDesc { get; set; }
        public int? DeductibleTypeId { get; set; }
        public int? DeductibleCategoryId { get; set; }
        public string DeductibleTypeDesc { get; set; }
        public decimal? DeductibleCategoryValue { get; set; }
        public int? StudentStatusId { get; set; }
        public string StudentStatusDesc { get; set; }
        public int? NotePredefiniedId { get; set; }
        public string NotePredefiniedDesc { get; set; }
        public bool? AutoSaveEnabled { get; set; }
        public int? AutoSaveMinutes { get; set; }
        public int? providerTypeId { get; set; }
        public string ProviderName { get; set; }
        public int? MunicipioId { get; set; }
        public string MunicipioDesc { get; set; }

        public class Parameter
        {
            public string DropDownType { get; set; }
            public int? CorpId { get; set; }
            public int? CompanyId { get; set; }
            public int? ProjectId { get; set; }
            public int? RegionId { get; set; }
            public int? CountryId { get; set; }
            public int? DomesticregId { get; set; }
            public int? StateProvId { get; set; }
            public int? CityId { get; set; }
            public int? OfficeId { get; set; }
            public int? CaseSeqNo { get; set; }
            public int? HistSeqNo { get; set; }
            public int? ContactId { get; set; }
            public int? AgentId { get; set; }
            public int? OccupGroupTypeId { get; set; }
            public bool? IsInsured { get; set; }
            public int? RequirementCatId { get; set; }
            public int? RiskGroupId { get; set; }
            public int? RiskDetId { get; set; }
            public int? TableTypeId { get; set; }
            public bool? ForExclusion { get; set; }
            public int? BlTypeId { get; set; }
            public int? BlId { get; set; }
            public int? PaymentSourceTypeId { get; set; }
            public int? PaymentSourceId { get; set; }
            public int? CurrencyId { get; set; }
            public string AbaNumber { get; set; }
            public bool? AppliedByFreqOrCountry { get; set; }
            public int? QuestionnaireId { get; set; }
            public int? QuestionId { get; set; }
            public int? ProductTypeId { get; set; }
            public int? RiskTypeId { get; set; }
            public bool? Sex { get; set; }
            public int? Age { get; set; }
            public int? FormCategoryId { get; set; }
            public int? ExclusionTypeId { get; set; }
            public string NameKey { get; set; }
            public int? CreditTypeId { get; set; }
            public int? LanguageId { get; set; }
            public int? UserId { get; set; }
            public int? ProviderId { get; set; }
            public int? DeductibleTypeId { get; set; }
            public int? ProviderTypeId { get; set; }
            public int? DirectoryId { get; set; }
        }
    }
}
