//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.SubmittedPolicies.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Global_Entities : DbContext
    {
        public Global_Entities()
            : base("name=Global_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_GET_POLICY_CONFIRMATION> VW_GET_POLICY_CONFIRMATION { get; set; }
        public virtual DbSet<VW_GET_POLICY_ISSUE> VW_GET_POLICY_ISSUE { get; set; }
        public virtual DbSet<VW_GET_POLICY_PRINT> VW_GET_POLICY_PRINT { get; set; }
        public virtual DbSet<VW_GET_POLICY_NEVER_ISSUED> VW_GET_POLICY_NEVER_ISSUED { get; set; }
        public virtual DbSet<VW_GET_POLICY_ISSUE_PROCESSING> VW_GET_POLICY_ISSUE_PROCESSING { get; set; }
    
        public virtual ObjectResult<SP_GET_POLICY_DATA_Result> SP_GET_POLICY_DATA(Nullable<int> company_Id, Nullable<int> project_Id, Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No)
        {
            var company_IdParameter = company_Id.HasValue ?
                new ObjectParameter("Company_Id", company_Id) :
                new ObjectParameter("Company_Id", typeof(int));
    
            var project_IdParameter = project_Id.HasValue ?
                new ObjectParameter("Project_Id", project_Id) :
                new ObjectParameter("Project_Id", typeof(int));
    
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_POLICY_DATA_Result>("SP_GET_POLICY_DATA", company_IdParameter, project_IdParameter, corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter);
        }
    
        public virtual ObjectResult<SP_GET_POLICY_RIDER_Result> SP_GET_POLICY_RIDER(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_POLICY_RIDER_Result>("SP_GET_POLICY_RIDER", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter);
        }
    
        public virtual ObjectResult<SP_GET_UW_DROPDOWN_Result> SP_GET_UW_DROPDOWN(string type, Nullable<int> corp_Id, Nullable<int> company_Id, Nullable<int> project_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No, Nullable<int> contact_Id, Nullable<int> agent_Id, Nullable<int> occupGroup_Type_Id, Nullable<bool> isInsured, Nullable<int> requirement_Cat_Id, Nullable<int> riskGroup_Id, Nullable<int> riskDet_Id, Nullable<int> table_Type_Id, Nullable<bool> for_Exclusion, Nullable<int> bl_Type_Id, Nullable<int> bl_Id, Nullable<int> payment_Source_Type_Id, Nullable<int> payment_Source_Id, Nullable<int> currency_Id, string aBA_Number, Nullable<bool> appliedByFreqOrCountry, Nullable<int> questionnaire_Id, Nullable<int> question_Id, Nullable<int> product_Type_Id, Nullable<int> risk_Type_Id, Nullable<bool> sex, Nullable<int> age, Nullable<int> form_Category_Id, Nullable<int> exclusion_Type_Id, string name_Key, Nullable<int> credit_Type_Id, Nullable<int> language_Id, Nullable<int> user_Id, Nullable<int> provider_Id)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var company_IdParameter = company_Id.HasValue ?
                new ObjectParameter("Company_Id", company_Id) :
                new ObjectParameter("Company_Id", typeof(int));
    
            var project_IdParameter = project_Id.HasValue ?
                new ObjectParameter("Project_Id", project_Id) :
                new ObjectParameter("Project_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            var contact_IdParameter = contact_Id.HasValue ?
                new ObjectParameter("Contact_Id", contact_Id) :
                new ObjectParameter("Contact_Id", typeof(int));
    
            var agent_IdParameter = agent_Id.HasValue ?
                new ObjectParameter("Agent_Id", agent_Id) :
                new ObjectParameter("Agent_Id", typeof(int));
    
            var occupGroup_Type_IdParameter = occupGroup_Type_Id.HasValue ?
                new ObjectParameter("OccupGroup_Type_Id", occupGroup_Type_Id) :
                new ObjectParameter("OccupGroup_Type_Id", typeof(int));
    
            var isInsuredParameter = isInsured.HasValue ?
                new ObjectParameter("IsInsured", isInsured) :
                new ObjectParameter("IsInsured", typeof(bool));
    
            var requirement_Cat_IdParameter = requirement_Cat_Id.HasValue ?
                new ObjectParameter("Requirement_Cat_Id", requirement_Cat_Id) :
                new ObjectParameter("Requirement_Cat_Id", typeof(int));
    
            var riskGroup_IdParameter = riskGroup_Id.HasValue ?
                new ObjectParameter("RiskGroup_Id", riskGroup_Id) :
                new ObjectParameter("RiskGroup_Id", typeof(int));
    
            var riskDet_IdParameter = riskDet_Id.HasValue ?
                new ObjectParameter("RiskDet_Id", riskDet_Id) :
                new ObjectParameter("RiskDet_Id", typeof(int));
    
            var table_Type_IdParameter = table_Type_Id.HasValue ?
                new ObjectParameter("Table_Type_Id", table_Type_Id) :
                new ObjectParameter("Table_Type_Id", typeof(int));
    
            var for_ExclusionParameter = for_Exclusion.HasValue ?
                new ObjectParameter("For_Exclusion", for_Exclusion) :
                new ObjectParameter("For_Exclusion", typeof(bool));
    
            var bl_Type_IdParameter = bl_Type_Id.HasValue ?
                new ObjectParameter("Bl_Type_Id", bl_Type_Id) :
                new ObjectParameter("Bl_Type_Id", typeof(int));
    
            var bl_IdParameter = bl_Id.HasValue ?
                new ObjectParameter("Bl_Id", bl_Id) :
                new ObjectParameter("Bl_Id", typeof(int));
    
            var payment_Source_Type_IdParameter = payment_Source_Type_Id.HasValue ?
                new ObjectParameter("Payment_Source_Type_Id", payment_Source_Type_Id) :
                new ObjectParameter("Payment_Source_Type_Id", typeof(int));
    
            var payment_Source_IdParameter = payment_Source_Id.HasValue ?
                new ObjectParameter("Payment_Source_Id", payment_Source_Id) :
                new ObjectParameter("Payment_Source_Id", typeof(int));
    
            var currency_IdParameter = currency_Id.HasValue ?
                new ObjectParameter("Currency_Id", currency_Id) :
                new ObjectParameter("Currency_Id", typeof(int));
    
            var aBA_NumberParameter = aBA_Number != null ?
                new ObjectParameter("ABA_Number", aBA_Number) :
                new ObjectParameter("ABA_Number", typeof(string));
    
            var appliedByFreqOrCountryParameter = appliedByFreqOrCountry.HasValue ?
                new ObjectParameter("AppliedByFreqOrCountry", appliedByFreqOrCountry) :
                new ObjectParameter("AppliedByFreqOrCountry", typeof(bool));
    
            var questionnaire_IdParameter = questionnaire_Id.HasValue ?
                new ObjectParameter("Questionnaire_Id", questionnaire_Id) :
                new ObjectParameter("Questionnaire_Id", typeof(int));
    
            var question_IdParameter = question_Id.HasValue ?
                new ObjectParameter("Question_Id", question_Id) :
                new ObjectParameter("Question_Id", typeof(int));
    
            var product_Type_IdParameter = product_Type_Id.HasValue ?
                new ObjectParameter("Product_Type_Id", product_Type_Id) :
                new ObjectParameter("Product_Type_Id", typeof(int));
    
            var risk_Type_IdParameter = risk_Type_Id.HasValue ?
                new ObjectParameter("Risk_Type_Id", risk_Type_Id) :
                new ObjectParameter("Risk_Type_Id", typeof(int));
    
            var sexParameter = sex.HasValue ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(bool));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var form_Category_IdParameter = form_Category_Id.HasValue ?
                new ObjectParameter("Form_Category_Id", form_Category_Id) :
                new ObjectParameter("Form_Category_Id", typeof(int));
    
            var exclusion_Type_IdParameter = exclusion_Type_Id.HasValue ?
                new ObjectParameter("Exclusion_Type_Id", exclusion_Type_Id) :
                new ObjectParameter("Exclusion_Type_Id", typeof(int));
    
            var name_KeyParameter = name_Key != null ?
                new ObjectParameter("Name_Key", name_Key) :
                new ObjectParameter("Name_Key", typeof(string));
    
            var credit_Type_IdParameter = credit_Type_Id.HasValue ?
                new ObjectParameter("Credit_Type_Id", credit_Type_Id) :
                new ObjectParameter("Credit_Type_Id", typeof(int));
    
            var language_IdParameter = language_Id.HasValue ?
                new ObjectParameter("Language_Id", language_Id) :
                new ObjectParameter("Language_Id", typeof(int));
    
            var user_IdParameter = user_Id.HasValue ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(int));
    
            var provider_IdParameter = provider_Id.HasValue ?
                new ObjectParameter("Provider_Id", provider_Id) :
                new ObjectParameter("Provider_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_UW_DROPDOWN_Result>("SP_GET_UW_DROPDOWN", typeParameter, corp_IdParameter, company_IdParameter, project_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter, contact_IdParameter, agent_IdParameter, occupGroup_Type_IdParameter, isInsuredParameter, requirement_Cat_IdParameter, riskGroup_IdParameter, riskDet_IdParameter, table_Type_IdParameter, for_ExclusionParameter, bl_Type_IdParameter, bl_IdParameter, payment_Source_Type_IdParameter, payment_Source_IdParameter, currency_IdParameter, aBA_NumberParameter, appliedByFreqOrCountryParameter, questionnaire_IdParameter, question_IdParameter, product_Type_IdParameter, risk_Type_IdParameter, sexParameter, ageParameter, form_Category_IdParameter, exclusion_Type_IdParameter, name_KeyParameter, credit_Type_IdParameter, language_IdParameter, user_IdParameter, provider_IdParameter);
        }
    
        public virtual ObjectResult<SP_GET_POLICY_AMMENDMENT_Result> SP_GET_POLICY_AMMENDMENT(Nullable<int> company_Id, Nullable<int> project_Id, Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No)
        {
            var company_IdParameter = company_Id.HasValue ?
                new ObjectParameter("Company_Id", company_Id) :
                new ObjectParameter("Company_Id", typeof(int));
    
            var project_IdParameter = project_Id.HasValue ?
                new ObjectParameter("Project_Id", project_Id) :
                new ObjectParameter("Project_Id", typeof(int));
    
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_POLICY_AMMENDMENT_Result>("SP_GET_POLICY_AMMENDMENT", company_IdParameter, project_IdParameter, corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter);
        }
    
        public virtual ObjectResult<SP_SET_POLICY_AMMENDMENT_DOCUMENT_Result> SP_SET_POLICY_AMMENDMENT_DOCUMENT(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No, Nullable<int> ammendment_Id, byte[] document_Binary, string document_Name, Nullable<System.DateTime> file_Expire_Date, Nullable<int> userId)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            var ammendment_IdParameter = ammendment_Id.HasValue ?
                new ObjectParameter("Ammendment_Id", ammendment_Id) :
                new ObjectParameter("Ammendment_Id", typeof(int));
    
            var document_BinaryParameter = document_Binary != null ?
                new ObjectParameter("Document_Binary", document_Binary) :
                new ObjectParameter("Document_Binary", typeof(byte[]));
    
            var document_NameParameter = document_Name != null ?
                new ObjectParameter("Document_Name", document_Name) :
                new ObjectParameter("Document_Name", typeof(string));
    
            var file_Expire_DateParameter = file_Expire_Date.HasValue ?
                new ObjectParameter("File_Expire_Date", file_Expire_Date) :
                new ObjectParameter("File_Expire_Date", typeof(System.DateTime));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SET_POLICY_AMMENDMENT_DOCUMENT_Result>("SP_SET_POLICY_AMMENDMENT_DOCUMENT", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter, ammendment_IdParameter, document_BinaryParameter, document_NameParameter, file_Expire_DateParameter, userIdParameter);
        }
    
        public virtual int SP_SET_POLICY_AMMENDMENT_STATUS_PENDING(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No, Nullable<int> ammendment_Id, Nullable<int> userId)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            var ammendment_IdParameter = ammendment_Id.HasValue ?
                new ObjectParameter("Ammendment_Id", ammendment_Id) :
                new ObjectParameter("Ammendment_Id", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SET_POLICY_AMMENDMENT_STATUS_PENDING", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter, ammendment_IdParameter, userIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_PAYMENTS_PAYMENTS_DOCUMENT_Result> SP_GET_PAYMENTS_PAYMENTS_DOCUMENT(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No, Nullable<int> doc_Category_Id, Nullable<int> doc_Type_Id, Nullable<int> document_Id)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            var doc_Category_IdParameter = doc_Category_Id.HasValue ?
                new ObjectParameter("Doc_Category_Id", doc_Category_Id) :
                new ObjectParameter("Doc_Category_Id", typeof(int));
    
            var doc_Type_IdParameter = doc_Type_Id.HasValue ?
                new ObjectParameter("Doc_Type_Id", doc_Type_Id) :
                new ObjectParameter("Doc_Type_Id", typeof(int));
    
            var document_IdParameter = document_Id.HasValue ?
                new ObjectParameter("Document_Id", document_Id) :
                new ObjectParameter("Document_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PAYMENTS_PAYMENTS_DOCUMENT_Result>("SP_GET_PAYMENTS_PAYMENTS_DOCUMENT", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter, doc_Category_IdParameter, doc_Type_IdParameter, document_IdParameter);
        }
    
        public virtual ObjectResult<SP_SET_POLICY_REJECT_Result> SP_SET_POLICY_REJECT(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No, Nullable<int> step_Type_Id, Nullable<int> step_Id, Nullable<int> step_Case_No, string note_Desc, Nullable<int> userId)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            var step_Type_IdParameter = step_Type_Id.HasValue ?
                new ObjectParameter("Step_Type_Id", step_Type_Id) :
                new ObjectParameter("Step_Type_Id", typeof(int));
    
            var step_IdParameter = step_Id.HasValue ?
                new ObjectParameter("Step_Id", step_Id) :
                new ObjectParameter("Step_Id", typeof(int));
    
            var step_Case_NoParameter = step_Case_No.HasValue ?
                new ObjectParameter("Step_Case_No", step_Case_No) :
                new ObjectParameter("Step_Case_No", typeof(int));
    
            var note_DescParameter = note_Desc != null ?
                new ObjectParameter("Note_Desc", note_Desc) :
                new ObjectParameter("Note_Desc", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SET_POLICY_REJECT_Result>("SP_SET_POLICY_REJECT", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter, step_Type_IdParameter, step_IdParameter, step_Case_NoParameter, note_DescParameter, userIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_POLICY_NEVER_ISSUED_INFO_Result> SP_GET_POLICY_NEVER_ISSUED_INFO(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_POLICY_NEVER_ISSUED_INFO_Result>("SP_GET_POLICY_NEVER_ISSUED_INFO", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter);
        }
    
        public virtual ObjectResult<SP_SET_POLICY_NERVER_ISSUED_Result> SP_SET_POLICY_NERVER_ISSUED(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No, Nullable<int> step_Type_Id, Nullable<int> step_Id, Nullable<int> step_Case_No, Nullable<int> userId)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            var step_Type_IdParameter = step_Type_Id.HasValue ?
                new ObjectParameter("Step_Type_Id", step_Type_Id) :
                new ObjectParameter("Step_Type_Id", typeof(int));
    
            var step_IdParameter = step_Id.HasValue ?
                new ObjectParameter("Step_Id", step_Id) :
                new ObjectParameter("Step_Id", typeof(int));
    
            var step_Case_NoParameter = step_Case_No.HasValue ?
                new ObjectParameter("Step_Case_No", step_Case_No) :
                new ObjectParameter("Step_Case_No", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SET_POLICY_NERVER_ISSUED_Result>("SP_SET_POLICY_NERVER_ISSUED", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter, step_Type_IdParameter, step_IdParameter, step_Case_NoParameter, userIdParameter);
        }
    
        public virtual ObjectResult<SP_SET_POLICY_NERVER_ISSUED_EDIT_Result> SP_SET_POLICY_NERVER_ISSUED_EDIT(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No, Nullable<int> step_Type_Id, Nullable<int> step_Id, Nullable<int> step_Case_No, Nullable<int> note_Id, string note_Desc, Nullable<int> step_Reason_Id, Nullable<bool> penalty, Nullable<int> userId)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            var step_Type_IdParameter = step_Type_Id.HasValue ?
                new ObjectParameter("Step_Type_Id", step_Type_Id) :
                new ObjectParameter("Step_Type_Id", typeof(int));
    
            var step_IdParameter = step_Id.HasValue ?
                new ObjectParameter("Step_Id", step_Id) :
                new ObjectParameter("Step_Id", typeof(int));
    
            var step_Case_NoParameter = step_Case_No.HasValue ?
                new ObjectParameter("Step_Case_No", step_Case_No) :
                new ObjectParameter("Step_Case_No", typeof(int));
    
            var note_IdParameter = note_Id.HasValue ?
                new ObjectParameter("Note_Id", note_Id) :
                new ObjectParameter("Note_Id", typeof(int));
    
            var note_DescParameter = note_Desc != null ?
                new ObjectParameter("Note_Desc", note_Desc) :
                new ObjectParameter("Note_Desc", typeof(string));
    
            var step_Reason_IdParameter = step_Reason_Id.HasValue ?
                new ObjectParameter("Step_Reason_Id", step_Reason_Id) :
                new ObjectParameter("Step_Reason_Id", typeof(int));
    
            var penaltyParameter = penalty.HasValue ?
                new ObjectParameter("Penalty", penalty) :
                new ObjectParameter("Penalty", typeof(bool));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SET_POLICY_NERVER_ISSUED_EDIT_Result>("SP_SET_POLICY_NERVER_ISSUED_EDIT", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter, step_Type_IdParameter, step_IdParameter, step_Case_NoParameter, note_IdParameter, note_DescParameter, step_Reason_IdParameter, penaltyParameter, userIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_POLICY_REJECT_INFO_Result> SP_GET_POLICY_REJECT_INFO(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_POLICY_REJECT_INFO_Result>("SP_GET_POLICY_REJECT_INFO", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter);
        }
    
        public virtual ObjectResult<SP_GET_POLICY_DOCUMENT_INFO_Result> SP_GET_POLICY_DOCUMENT_INFO(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_POLICY_DOCUMENT_INFO_Result>("SP_GET_POLICY_DOCUMENT_INFO", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter);
        }
    
        public virtual ObjectResult<SP_SET_PL_PCY_STATUS_CHANGE_Result> SP_SET_PL_PCY_STATUS_CHANGE(Nullable<int> corp_Id, Nullable<int> region_Id, Nullable<int> country_Id, Nullable<int> domesticreg_Id, Nullable<int> state_Prov_Id, Nullable<int> city_Id, Nullable<int> office_Id, Nullable<int> case_Seq_No, Nullable<int> hist_Seq_No, Nullable<int> status_Change_Type_Id, Nullable<int> policy_Status_Id, Nullable<int> status_Change_Id, Nullable<int> userId)
        {
            var corp_IdParameter = corp_Id.HasValue ?
                new ObjectParameter("Corp_Id", corp_Id) :
                new ObjectParameter("Corp_Id", typeof(int));
    
            var region_IdParameter = region_Id.HasValue ?
                new ObjectParameter("Region_Id", region_Id) :
                new ObjectParameter("Region_Id", typeof(int));
    
            var country_IdParameter = country_Id.HasValue ?
                new ObjectParameter("Country_Id", country_Id) :
                new ObjectParameter("Country_Id", typeof(int));
    
            var domesticreg_IdParameter = domesticreg_Id.HasValue ?
                new ObjectParameter("Domesticreg_Id", domesticreg_Id) :
                new ObjectParameter("Domesticreg_Id", typeof(int));
    
            var state_Prov_IdParameter = state_Prov_Id.HasValue ?
                new ObjectParameter("State_Prov_Id", state_Prov_Id) :
                new ObjectParameter("State_Prov_Id", typeof(int));
    
            var city_IdParameter = city_Id.HasValue ?
                new ObjectParameter("City_Id", city_Id) :
                new ObjectParameter("City_Id", typeof(int));
    
            var office_IdParameter = office_Id.HasValue ?
                new ObjectParameter("Office_Id", office_Id) :
                new ObjectParameter("Office_Id", typeof(int));
    
            var case_Seq_NoParameter = case_Seq_No.HasValue ?
                new ObjectParameter("Case_Seq_No", case_Seq_No) :
                new ObjectParameter("Case_Seq_No", typeof(int));
    
            var hist_Seq_NoParameter = hist_Seq_No.HasValue ?
                new ObjectParameter("Hist_Seq_No", hist_Seq_No) :
                new ObjectParameter("Hist_Seq_No", typeof(int));
    
            var status_Change_Type_IdParameter = status_Change_Type_Id.HasValue ?
                new ObjectParameter("Status_Change_Type_Id", status_Change_Type_Id) :
                new ObjectParameter("Status_Change_Type_Id", typeof(int));
    
            var policy_Status_IdParameter = policy_Status_Id.HasValue ?
                new ObjectParameter("Policy_Status_Id", policy_Status_Id) :
                new ObjectParameter("Policy_Status_Id", typeof(int));
    
            var status_Change_IdParameter = status_Change_Id.HasValue ?
                new ObjectParameter("Status_Change_Id", status_Change_Id) :
                new ObjectParameter("Status_Change_Id", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SET_PL_PCY_STATUS_CHANGE_Result>("SP_SET_PL_PCY_STATUS_CHANGE", corp_IdParameter, region_IdParameter, country_IdParameter, domesticreg_IdParameter, state_Prov_IdParameter, city_IdParameter, office_IdParameter, case_Seq_NoParameter, hist_Seq_NoParameter, status_Change_Type_IdParameter, policy_Status_IdParameter, status_Change_IdParameter, userIdParameter);
        }
    }
}
