using System.Collections.Generic;
using System.Linq;
using DATA.UnderWriting.Data;
using DATA.UnderWriting.Repositories.Base;
using Entity.UnderWriting.Entities;

namespace DATA.UnderWriting.Repositories.Global
{
    public class DropDownRepository : GlobalRepository
    {
        public DropDownRepository(GlobalEntityDataModel globalModel, GlobalEntities globalModelExtended) : base(globalModel, globalModelExtended) { }

        public virtual IEnumerable<DropDown> GetByType(DropDown.Parameter parameters)
        {

            IEnumerable<DropDown> result;
            IEnumerable<SP_GET_UW_DROPDOWN_Result> temp;

            temp = globalModel.SP_GET_UW_DROPDOWN(
                        parameters.DropDownType,
                        parameters.CorpId,
                        parameters.CompanyId,
                        parameters.ProjectId,
                        parameters.RegionId,
                        parameters.CountryId,
                        parameters.DomesticregId,
                        parameters.StateProvId,
                        parameters.CityId,
                        parameters.OfficeId,
                        parameters.CaseSeqNo,
                        parameters.HistSeqNo,
                        parameters.ContactId,
                        parameters.AgentId,
                        parameters.OccupGroupTypeId,
                        parameters.IsInsured,
                        parameters.RequirementCatId,
                        parameters.RiskGroupId,
                        parameters.RiskDetId,
                        parameters.TableTypeId,
                        parameters.ForExclusion,
                        parameters.BlTypeId,
                        parameters.BlId,
                        parameters.PaymentSourceTypeId,
                        parameters.PaymentSourceId,
                        parameters.CurrencyId,
                        parameters.AbaNumber,
                        parameters.AppliedByFreqOrCountry,
                        parameters.QuestionnaireId,
                        parameters.QuestionId,
                        parameters.ProductTypeId,
                        parameters.RiskTypeId,
                        parameters.Sex,
                        parameters.Age,
                        parameters.FormCategoryId,
                        parameters.ExclusionTypeId,
                        parameters.NameKey,
                        parameters.CreditTypeId,
                        parameters.LanguageId,
                        parameters.UserId,
                        parameters.ProviderId,
                        parameters.DeductibleTypeId
                );

            result = temp
                .Select(dd => new DropDown
                {
                    AgentId = dd.Agent_Id,
                    AgentName = dd.Agent_Name,
                    CityDesc = dd.City_Desc,
                    CityId = dd.City_Id,
                    CorpId = dd.Corp_Id,
                    CountryId = dd.Country_Id,
                    DirTypeShortDesc = dd.Dir_Type_Short_Desc,
                    DirectoryTypeId = dd.Directory_Type_Id,
                    DomesticregId = dd.Domesticreg_Id,
                    GlobalCountryDesc = dd.Global_Country_Desc,
                    MaritalStatId = dd.Marital_Stat_Id,
                    MaritalStatusDesc = dd.Marital_Status_Desc,
                    OccupationDesc = dd.Occupation_Desc,
                    OccupationId = dd.Occupation_Id,
                    OccupGroupTypeId = dd.OccupGroup_Type_Id,
                    OfficeDesc = dd.Office_Desc,
                    OfficeId = dd.Office_Id,
                    PolicyStatusDesc = dd.Policy_Status_Desc,
                    PolicyStatusId = dd.Policy_Status_Id,
                    RegionId = dd.Region_Id,
                    StateProvId = dd.State_Prov_Id,
                    CaseSeqNo = dd.Case_Seq_No,
                    HistSeqNo = dd.Hist_Seq_No,
                    ContactId = dd.Contact_Id,
                    ContactRoleTypeId = dd.Contact_Role_Type_Id,
                    RoleDesc = dd.Role_Desc,
                    SmokerId = dd.Smoker_Id,
                    SmokerDesc = dd.Smoker_Desc,
                    GenderId = dd.Gender_Id,
                    GenderDesc = dd.Gender_Desc,
                    ContactTypeId = dd.Contact_Id_Type,
                    ContactTypeIdDesc = dd.Contact_Id_Type_Desc,
                    RelationshipId = dd.Relationship_Id,
                    RelationshipDesc = dd.Relationship_Desc,
                    StateProvDesc = dd.State_Prov_Desc,
                    OccupationGroupDesc = dd.Occupation_Group_Desc,
                    AmmendTypeId = dd.Ammend_Type_Id,
                    AmmendTypeDesc = dd.Ammend_Type_Desc,
                    InsuredScopeId = dd.Insured_Scope_Id,
                    InsuredScopeDesc = dd.Insured_Scope_Desc,
                    RiderTypeId = dd.Rider_Type_Id,
                    CodeName = dd.Code_Name,
                    RiderStatusId = dd.Rider_Status_Id,
                    RiderStatusDesc = dd.Rider_Status_Desc,
                    PaymentStatusDesc = dd.Payment_Status_Desc,
                    PaymentStatusId = dd.Payment_Status_id,
                    PolicyNo = dd.Policy_No,
                    RequirementCatId = dd.Requirement_Cat_Id,
                    RequirementCatDesc = dd.Requirement_Cat_Desc,
                    RequirementTypeId = dd.Requirement_Type_Id,
                    RequirementTypeDesc = dd.Requirement_Type_Desc,
                    ExcerciseId = dd.Excercise_Id,
                    ExcerciseDesc = dd.Excercise_Desc,
                    DrugId = dd.Drug_Id,
                    DrugDesc = dd.Drug_Desc,
                    ElementDesc = dd.Element_Desc,
                    ElementId = dd.Element_Id,
                    GridId = dd.Grid_Id,
                    PageId = dd.Page_Id,
                    RiskDetDesc = dd.RiskDet_Desc,
                    RiskDetId = dd.RiskDet_Id,
                    RiskGroupDesc = dd.RiskGroup_Desc,
                    RiskGroupId = dd.RiskGroup_Id,
                    RatingId = dd.Rating_Id,
                    RatingValue = dd.Rating_Value,
                    TableTypeId = dd.Table_Type_Id,
                    MedicalTestId = dd.Medical_Test_Id,
                    RequirementId = dd.Requirement_Id,
                    ColumnId = dd.Column_Id,
                    RiskTypeId = dd.Risk_Type_Id,
                    CurrencyId = dd.Currency_Id,
                    CurrencyDesc = dd.Currency_Desc,
                    BlTypeId = dd.Bl_Type_Id,
                    BlId = dd.Bl_Id,
                    BlDesc = dd.Bl_Desc,
                    ProductId = dd.Product_Id,
                    ProductDesc = dd.Product_Desc,
                    PolicySerieId = dd.Policy_Serie_Id,
                    SerieCode = dd.Serie_Code,
                    SerieDesc = dd.Serie_Desc,
                    PaymentFreqTypeDesc = dd.Payment_Freq_Type_Desc,
                    PaymentFreqTypeId = dd.Payment_Freq_Type_Id,
                    ProfileTypeDesc = dd.PROFILE_TYPE_DESC,
                    ProfileTypeId = dd.PROFILE_TYPE_ID,
                    NoteReferenceTypeId = dd.Note_Reference_Type_Id,
                    NoteReferenceTypeDesc = dd.Note_Reference_Type_Desc,
                    DocTypeId = dd.Doc_Type_Id,
                    DocCategoryId = dd.Doc_Category_Id,
                    DocCategoryDesc = dd.Doc_Category_Desc,
                    Counts = dd.Counts,
                    ContributionTypeId = dd.Contribution_Type_Id,
                    ContributionTypeDesc = dd.Contribution_Type_Desc,
                    StepTypeId = dd.Step_Type_Id,
                    StepId = dd.Step_Id,
                    StepCode = dd.Step_Code,
                    StepDesc = dd.Step_Desc,
                    PaymentTypeId = dd.Payment_Type_Id,
                    PaymentDesc = dd.Payment_Desc,
                    PaymentSourceTypeId = dd.Payment_Source_Type_Id,
                    PaymentSourceId = dd.Payment_Source_Id,
                    PaymentSourceDesc = dd.Payment_Source_Desc,
                    CardTypeId = dd.Card_Type_Id,
                    AccountDesc = dd.Account_Desc,
                    CardTypeDesc = dd.Card_Type_Desc,
                    PaymentControlId = dd.Payment_Control_Id,
                    AccountTypeId = dd.Account_Type_Id,
                    BankId = dd.Bank_Id,
                    BankDesc = dd.Bank_Desc,
                    AbaNumber = dd.ABA_Number,
                    ActionId = dd.Action_Id,
                    ActionDesc = dd.Action_Desc,
                    NoteTypeId = dd.Note_Type_Id,
                    NoteTypeDesc = dd.Note_Type_Desc,
                    HomeStatusId = dd.Home_Status_Id,
                    HomeStatusDesc = dd.Home_Status_Desc,
                    LaborPlayedId = dd.Labor_Played_Id,
                    LaborPlayedDesc = dd.Labor_Played_Desc,
                    Namekey = dd.Namekey,
                    ScaleId = dd.Scale_Id,
                    ScaleTypeId = dd.Scale_Type_Id,
                    ScaleDesc = dd.Scale_Desc,
                    DiseaseDesc = dd.Disease_Desc,
                    DiseaseId = dd.Disease_Id,
                    QuestionId = dd.Question_Id,
                    QuestionnaireId = dd.Questionnaire_Id,
                    Modifiable = dd.MODIFIABLE,
                    ProductTypeId = dd.Product_Type_Id,
                    RiskTypeDesc = dd.Risk_Type_Desc,
                    FormId = dd.Form_Id,
                    FormDesc = dd.Form_Desc,
                    FormCategoryId = dd.Form_Category_Id,
                    FormCatDesc = dd.Form_Cat_Desc,
                    RiderId = dd.Rider_Id,
                    ExclusionTypeId = dd.Exclusion_Type_Id,
                    ExclusionTypeDesc = dd.Exclusion_Type_Desc,
                    ExclusionId = dd.Exclusion_Id,
                    ExclusionDesc = dd.Exclusion_Desc,
                    CreditId = dd.Credit_Id,
                    CreditDesc = dd.Credit_Desc,
                    CreditReasonId = dd.Credit_Reason_Id,
                    CreditReasonDesc = dd.Credit_Reason_Desc,
                    RequestedBy = dd.Requested_By,
                    UnderwritingId = dd.UnderwritingId,
                    UnderwritingName = dd.UnderwritingName,
                    LanguageId = dd.Language_Id,
                    LanguageDesc = dd.Language_Desc,
                    ImageName = dd.Image_Name,
                    CreditTypeId = dd.Credit_Type_Id,
                    RatingTypeId = dd.Rating_Type_Id,
                    RatingTypeDesc = dd.Rating_Type_Desc,
                    PrintStatus = dd.Print_Status,
                    GlobalCountryDescTimeZone = dd.Global_Time_Zone_Desc,
                    StepReasonId = dd.Step_Reason_Id,
                    StepReasonDesc = dd.Step_Reason_Desc,
                    BloodTypeId = dd.Blood_Type_Id,
                    BloodTypeDesc = dd.Blood_Type_Desc,
                    RejectReasonId = dd.Reject_Reason_Id,
                    RejectReasonDesc = dd.Reject_Reason_Desc,
                    ProviderId = dd.Provider_Id,
                    TransactionTypeCatalogId = dd.Transaction_Type_Catalog_Id,
                    ProviderTransactionTypeId = dd.Provider_Transaction_Type_Id,
                    TransactionTypeCatalogDesc = dd.Transaction_Type_Catalog_Desc,
                    ResponseCode = dd.Response_Code,
                    ResponseDesc = dd.Response_Desc,
                    ConfigurationValue = dd.Configuration_Value,
                    CompanyId = dd.Company_Id,
                    CompanyDesc = dd.Company_Desc,
                    DeductibleTypeId = dd.Deductible_Type_Id,
                    DeductibleCategoryId = dd.Deductible_Category_Id,
                    DeductibleTypeDesc = dd.Deductible_Type_Desc,
                    DeductibleCategoryValue = dd.Deductible_Category_Value,
                    StudentStatusId = dd.Student_Status_Id,
                    StudentStatusDesc = dd.Student_Status_Desc,
                    NotePredefiniedId = dd.Note_Predefinied_Id,
                    NotePredefiniedDesc = dd.Note_Predefinied_Desc,
                    AutoSaveEnabled = dd.AutoSaveEnabled,
                    AutoSaveMinutes = dd.AutoSaveMinutes,
                    MunicipioId = dd.Form_Id,
                    MunicipioDesc = dd.Form_Desc
                })
                .ToArray();

            return
                result;
        }
    }
}
