//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_ST_COVERAGE_Result
    {
        public int Corp_Id { get; set; }
        public int Coverage_Type_Id { get; set; }
        public int Coverage_Id { get; set; }
        public string Coverage_Desc { get; set; }
        public string NameKey { get; set; }
    }
}
