//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_PL_POLICY_PROPERTY_INSURED_DETAIL_FEATURE_Result
    {
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Serial_Key { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Corp_Id { get; set; }
        public long Unique_Property_Id { get; set; }
        public int Seq_Id { get; set; }
        public string Description { get; set; }
        public string Capacity { get; set; }
        public string Author { get; set; }
        public Nullable<int> Position_Id { get; set; }
        public Nullable<int> Certificate_Id { get; set; }
        public Nullable<int> Measure_Type_Id { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public Nullable<decimal> Deductible { get; set; }
        public Nullable<decimal> Minimum_Deductible { get; set; }
        public int Feature_Property_Status_Id { get; set; }
        public string Measure_Type_Desc { get; set; }
        public string Position_Desc { get; set; }
        public string Certificate_Desc { get; set; }
        public string Type { get; set; }
    }
}
