//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class sp_get_customerplanopbaldet_Result
    {
        public Nullable<long> customerno { get; set; }
        public long customerplanno { get; set; }
        public Nullable<decimal> currentvalue { get; set; }
        public Nullable<decimal> planyear { get; set; }
        public Nullable<decimal> targetamount { get; set; }
        public Nullable<decimal> minimumpremium { get; set; }
        public string frequencytypecode { get; set; }
        public Nullable<decimal> periodicpremium { get; set; }
        public Nullable<int> noofunpaidpremiums { get; set; }
        public string investmentprofilecode { get; set; }
        public Nullable<decimal> monthlyinsurancecost { get; set; }
        public Nullable<decimal> forceaccountvalue { get; set; }
        public Nullable<decimal> openingbalance { get; set; }
        public string calculatetypeobcode { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public string productcode { get; set; }
        public Nullable<System.DateTime> datesynced { get; set; }
        public Nullable<long> recordid { get; set; }
        public Nullable<decimal> totalamountpaid { get; set; }
        public Nullable<decimal> nopaymentsrecieved { get; set; }
        public Nullable<decimal> amountdue { get; set; }
        public Nullable<decimal> illustrationmonth { get; set; }
        public Nullable<decimal> forcetarget { get; set; }
        public string isoverride { get; set; }
        public Nullable<int> fullpaymentyear { get; set; }
        public Nullable<decimal> expectedpremiums { get; set; }
        public Nullable<decimal> adjustedaccountvalue { get; set; }
        public Nullable<decimal> insuredamount { get; set; }
    }
}
