//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class uftWordTokens_Result
    {
        public int SeqNo { get; set; }
        public string Item { get; set; }
        public Nullable<int> TokenType { get; set; }
    }
}
