//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_GENERATESECURITYQUESTION_Result
    {
        public string contact_id { get; set; }
        public Nullable<int> questionnaire_id { get; set; }
        public Nullable<int> call_meeting_type_id { get; set; }
        public string call_meeting_type_desc { get; set; }
        public int template_type_id { get; set; }
        public string template_type_desc { get; set; }
        public int template_id { get; set; }
        public Nullable<int> question_id { get; set; }
        public string textual_answer_hash { get; set; }
        public string answ_desc { get; set; }
        public string QuestionPool { get; set; }
    }
}
