//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedor()
        {
            this.cuentas_x_pagar = new HashSet<cuentas_x_pagar>();
            this.ingreso = new HashSet<ingreso>();
        }
    
        public int idproveedor { get; set; }
        public string razon_social { get; set; }
        public string sector_comercial { get; set; }
        public string tipo_documento { get; set; }
        public string num_documento { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string url { get; set; }
        public Nullable<bool> statu { get; set; }
        public Nullable<System.DateTime> FechaAdiciona { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public string UsuarioAdiciona { get; set; }
        public string UsuarioModifica { get; set; }
        public string HostName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentas_x_pagar> cuentas_x_pagar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingreso> ingreso { get; set; }
    }
}
