// <auto-generated />
namespace STL.POS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v068 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v068));
        
        string IMigrationMetadata.Id
        {
            get { return "201508282132227_v0.6.8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
