//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.NewBusiness.NewBusiness.UserControls.Beneficiaries {
    
    
    public partial class WUCAdditionalInsured {
        
        /// <summary>
        /// WUCMainBeneficiaries control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WEB.NewBusiness.NewBusiness.UserControls.Beneficiaries.WUCBeneficiaries WUCMainBeneficiaries;
        
        /// <summary>
        /// WUCContingentBeneficiaries control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WEB.NewBusiness.NewBusiness.UserControls.Beneficiaries.WUCBeneficiaries WUCContingentBeneficiaries;
    }
}
