//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STL.POS.Data.NewVersion.EdmxModel
{
    using System;
    
    public partial class SP_GET_PRODUCTS_SYSFLEX_Result
    {
        public Nullable<int> Ramo { get; set; }
        public Nullable<int> SubRamo { get; set; }
        public string SubRamoName { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> PorcientoInicial { get; set; }
        public Nullable<int> PorcientoFinal { get; set; }
        public Nullable<int> MontoInicial { get; set; }
        public Nullable<int> MontoFinal { get; set; }
        public Nullable<int> Prima { get; set; }
        public Nullable<int> Porciento { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Calculo { get; set; }
        public Nullable<int> Compania { get; set; }
        public Nullable<int> TipoPoliza { get; set; }
        public string DescTipoPoliza { get; set; }
        public Nullable<bool> RequiereInspeccion { get; set; }
        public Nullable<int> IdCapacidad { get; set; }
        public string DescCapacidad { get; set; }
        public Nullable<int> IdUso { get; set; }
        public string DescUso { get; set; }
        public Nullable<int> IdTipoVehiculo { get; set; }
        public string DescTipoVehiculo { get; set; }
        public Nullable<int> YearQty { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
