//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_SET_OFFICE_DEPARTMENT_MESSAGE_Result
    {
        public Nullable<int> Message_Id { get; set; }
        public Nullable<int> Corp_Id { get; set; }
        public Nullable<int> Region_Id { get; set; }
        public Nullable<int> Country_Id { get; set; }
        public Nullable<int> DomesticReg_Id { get; set; }
        public Nullable<int> State_Prov_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> Office_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
    }
}
