//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class sp_get_ruleparametervaluesdet_Result
    {
        public int ruleparametervalueno { get; set; }
        public Nullable<int> ruleparameterno { get; set; }
        public Nullable<decimal> ruleparametervalue { get; set; }
        public string productcode { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<System.DateTime> datesynced { get; set; }
    }
}
