//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_REQUIREMENT_DOCUMENT_ONBASE_Result
    {
        public int Doc_Type_Id { get; set; }
        public int Doc_Category_Id { get; set; }
        public string On_Base_Name_Key { get; set; }
        public string DescriptionName { get; set; }
        public string Clasification { get; set; }
    }
}
