//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class spu_GetWeekInterval_Result
    {
        public Nullable<int> Semana { get; set; }
        public Nullable<System.DateTime> FirstDay { get; set; }
        public Nullable<System.DateTime> LastDay { get; set; }
    }
}
