// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
public sealed partial class v053 : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(v053));
    
    string IMigrationMetadata.Id
    {
        get { return "201508211807354_v0.5.3"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return null; }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
