//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class recentillustration_Result
    {
        public string plandate { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string product { get; set; }
        public string productcode { get; set; }
        public string plangroup { get; set; }
        public Nullable<decimal> premiumamount { get; set; }
        public Nullable<decimal> insuredamount { get; set; }
        public Nullable<decimal> annuityamount { get; set; }
    }
}
