//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATL.EditCoberturas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysFlexSegurosEntities : DbContext
    {
        public SysFlexSegurosEntities()
            : base("name=SysFlexSegurosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<P_PolizaCoberturasMov> P_PolizaCoberturasMov { get; set; }
        public virtual DbSet<Reaseguro_INVOCE_Report_VIEW> Reaseguro_INVOCE_Report_VIEW { get; set; }
        public virtual DbSet<P_PolizaHeaderMov> P_PolizaHeaderMov { get; set; }
    }
}
