//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_DOCUMENT_TYPE_LIST_Result
    {
        public Nullable<int> ID { get; set; }
        public Nullable<int> DocumentCategoryID { get; set; }
        public string Description { get; set; }
        public string DefinitionCode { get; set; }
        public string System { get; set; }
    }
}
