//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_vw_New_Business_Login_Select_Result
    {
        public int ID { get; set; }
        public string NameId { get; set; }
        public string Type { get; set; }
        public string User_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Name { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Email_I { get; set; }
        public string Email_II { get; set; }
        public string Address_I { get; set; }
        public string Address_II { get; set; }
        public string Address_III { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Country { get; set; }
        public string Zip_Code { get; set; }
        public int Rol { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
