//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STL.POS.Data.NewVersion.EdmxModel
{
    using System;
    
    public partial class SP_GET_VEHICLE_FUEL_TYPE_BY_MODEL_Result
    {
        public Nullable<int> VehicleFuelTypeIdSysflex { get; set; }
        public Nullable<int> Make_Id { get; set; }
        public Nullable<int> Model_Id { get; set; }
        public string VehicleFuelTypeDesc { get; set; }
    }
}
