//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_PL_POLICY_PROPERTY_INSURED_DET_Result
    {
        public int Corp_Id { get; set; }
        public int Region_Id { get; set; }
        public int Country_Id { get; set; }
        public int Domesticreg_Id { get; set; }
        public int State_Prov_Id { get; set; }
        public int City_Id { get; set; }
        public int Office_Id { get; set; }
        public int Case_Seq_No { get; set; }
        public int Hist_Seq_No { get; set; }
        public int Property_Id { get; set; }
        public int Seq_Id { get; set; }
        public long Unique_Property_Id { get; set; }
        public int Insurable_Type_Id { get; set; }
        public int Insured_Detail_Type_Id { get; set; }
        public int Equipment_Type_Id { get; set; }
        public int Condition_Id { get; set; }
        public int Electric_System_Type_Id { get; set; }
        public int Fire_Protection_Equipment_Type_Id { get; set; }
        public int Organization_Type_Id { get; set; }
        public int Security_Type_Id { get; set; }
        public int Bl_Type_Id { get; set; }
        public int Bl_Id { get; set; }
        public int Product_Id { get; set; }
        public int Reinsurance_Id { get; set; }
        public decimal Reinsurance_Amount { get; set; }
        public Nullable<System.DateTime> Insured_Date { get; set; }
        public decimal Insured_Amount { get; set; }
        public decimal Rate { get; set; }
        public decimal Premium_Amount { get; set; }
        public decimal Base_Premium_Amount { get; set; }
        public decimal Deductible_Percentage { get; set; }
        public decimal Deductible_Amount { get; set; }
        public decimal Minimum_Deductible_Amount { get; set; }
        public bool Requires_Inspection { get; set; }
        public bool Inspected { get; set; }
        public bool Endorsement_Clarifying { get; set; }
        public bool Endorsement { get; set; }
        public string Endorsement_Beneficiary { get; set; }
        public string Endorsement_Beneficiary_Rnc { get; set; }
        public Nullable<decimal> Endorsement_Amount { get; set; }
        public string Endorsement_Contact_Name { get; set; }
        public string Endorsement_Contact_Phone { get; set; }
        public string Endorsement_Contact_Email { get; set; }
        public int Property_Detail_Status_Id { get; set; }
        public string Source_Id { get; set; }
        public string Graduation_Year { get; set; }
        public string Underground_Features { get; set; }
        public string Project_Account_With_Guarantee_or_Deposit { get; set; }
        public string Deductible_In_Days { get; set; }
        public string Inside_Business { get; set; }
        public string Project_Description { get; set; }
        public string GPS { get; set; }
        public string Specialty { get; set; }
        public string Exequatur { get; set; }
        public string Penalty_For_Delayed_Project_Delivery { get; set; }
        public string Contractor_Experience_In_Similar_Projects { get; set; }
        public string Machinery_Operator_Experience { get; set; }
        public string Subcontractor_Experience { get; set; }
        public string Exequatur_Registration_Date { get; set; }
        public string Policy_Format { get; set; }
        public string Out_of_Local_Bank_Deposits { get; set; }
        public string Equipment_Maintenance { get; set; }
        public string Construction_Material { get; set; }
        public string Control_Measures { get; set; }
        public string Security_Measures { get; set; }
        public string Minimum_Deductible { get; set; }
        public string Name_Centre { get; set; }
        public string Other_Risks { get; set; }
        public string Special_Dangers { get; set; }
        public string Compensation_Period { get; set; }
        public string Equipment_Weight { get; set; }
        public string Percent_of_Coinsurance_Agreed { get; set; }
        public string Civil_Liability { get; set; }
        public string Risk_of_Tempest { get; set; }
        public string Catastrophic_Risks { get; set; }
        public string Security_Protection_During_Construction_Process { get; set; }
        public string Project_Has_Subcontractor { get; set; }
        public string The_Contractor_Has_Contractual_RC_Coverage { get; set; }
        public string Type_Coverage { get; set; }
        public string Project_Type { get; set; }
        public string Type_of_Equipment_Guard { get; set; }
        public string Type_Machinery { get; set; }
        public string University_Studies { get; set; }
        public string Use_Of_Machinery { get; set; }
        public string Gross_Profit { get; set; }
        public string Transport_Vehicles { get; set; }
        public string Surveillance { get; set; }
    }
}
