//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_SUMMARY_PAYMENTS_Result
    {
        public string Policy_No { get; set; }
        public Nullable<decimal> Due_Amount { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public Nullable<decimal> Paid_Amount { get; set; }
        public Nullable<System.DateTime> Paid_Date { get; set; }
        public Nullable<decimal> Base_Premium { get; set; }
        public Nullable<decimal> Exceptional_premium { get; set; }
        public Nullable<decimal> Base_Commision { get; set; }
        public Nullable<decimal> Base_Commision2 { get; set; }
        public Nullable<decimal> Exceptional_Commisions { get; set; }
        public Nullable<decimal> Exceptional2_Commisions { get; set; }
        public string Payment_Status_Desc { get; set; }
    }
}
