//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipLogs.Data.EF_MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipment()
        {
            this.ShipmentDetails = new HashSet<ShipmentDetail>();
        }
    
        public int ShipUniqueID { get; set; }
        public string CarrierName { get; set; }
        public string AccountNumber { get; set; }
        public string ShipmentNumber { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public Nullable<decimal> ShipmentWeight { get; set; }
        public Nullable<int> ShipmentQTY { get; set; }
        public string ShipPackageType { get; set; }
        public string Operator { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string ReceiverAttn { get; set; }
        public string ReceiverAddress { get; set; }
        public string ReceiverCity { get; set; }
        public string ReceiverState { get; set; }
        public string ReceiverZipCode { get; set; }
        public string ReceiverCountry { get; set; }
        public string ReceiverPhoneNumber { get; set; }
        public string ShipmentComments { get; set; }
        public Nullable<bool> Transit { get; set; }
        public Nullable<bool> Incoming { get; set; }
        public Nullable<bool> CommissionChecks { get; set; }
        public Nullable<bool> Materials { get; set; }
        public Nullable<bool> OtherContents { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentDetail> ShipmentDetails { get; set; }
    }
}
