//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATL.EditCoberturas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reaseguro_INVOCE_Report_VIEW
    {
        public string POLICY_NUMBER { get; set; }
        public decimal DOCUMENT_NUMBER { get; set; }
        public int DOCUMENT_TYPE { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string VEHICLE_PRODUCT { get; set; }
        public Nullable<int> VEHICLE_ITEM { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public Nullable<decimal> VEHICLE_AMOUNT { get; set; }
        public Nullable<decimal> DPA_AMOUNT { get; set; }
        public Nullable<decimal> DP_AMOUNT { get; set; }
        public Nullable<decimal> SERVICE_AMOUNT { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<int> MOv { get; set; }
    }
}
