//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.UnderWriting.Data
{
    using System;
    
    public partial class SP_GET_PL_RISK_RATING_CONDITION_PERCENTAGE_OVER_Result
    {
        public int Rating_Type_Id { get; set; }
        public string Min_Value { get; set; }
        public string Max_Value { get; set; }
    }
}
