//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateTrustGlobal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EN_AGENT_GP_COMMISSION
    {
        public int Corp_Id { get; set; }
        public int Agent_Id { get; set; }
        public bool No_Commission { get; set; }
        public bool Take_Vendor_Id { get; set; }
        public string Vendor_Id { get; set; }
        public bool Agent_Status { get; set; }
        public System.DateTime Create_Date { get; set; }
        public Nullable<System.DateTime> Modi_Date { get; set; }
        public int Create_UsrId { get; set; }
        public Nullable<int> Modi_UsrId { get; set; }
        public string Hostname { get; set; }
    }
}
