//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.NewBusiness.Common.Statistics
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StatisticsEntities : DbContext
    {
        public StatisticsEntities()
            : base("name=StatisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_GET_QUO_PL_POLICY_STATISTICS_BYMONTH> VW_GET_QUO_PL_POLICY_STATISTICS_BYMONTH { get; set; }
    }
}
